# Generated by Django 4.2.7 on 2023-11-06 01:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ToolsPage", "0002_idea_delete_page"),
    ]

    operations = [
        migrations.AddField(
            model_name="idea",
            name="likes",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
